cargo-features = ["strip"]

[package]
name = "rabbit-digger-pro"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "Just a stub"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.38"
tokio = { version = "1.5.0", features = ["full"] }
tokio-stream = { version = "0.1.6", features = ["net"] }
structopt = { version = "0.3.21", features = ["paw"] }
paw = "1.0.0"
log = { version = "0.4.13", features = ["release_max_level_debug"] }
env_logger = "0.8.2"
rabbit-digger = { version = "0.1", path = "./rabbit-digger" }
notify-stream = "0.1.1"
futures = "0.3"
pin-project-lite = "0.2.6"
serde_yaml = "0.8.15"
yaml-merge-keys = { version = "0.4.1", features = ["serde_yaml"] }
serde_json = "1.0"
serde = "1.0.119"
serde_derive = "1.0.119"
warp = { version = "0.3.1", default-features = false, optional = true }
rd-interface = { path = "./rabbit-digger/rd-interface/", version = "0.4" }

ss = { path = "./ss", optional = true }
trojan = { path = "./trojan", optional = true }

[features]
default = [ "api_server", "translate", "ss", "trojan" ]
translate = []
api_server = [ "warp" ]
local_log = [ "rabbit-digger/local_log" ]

[workspace]
members = [
    "ss",
]
exclude = ["rabbit-digger"]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = "symbols"
