server:
  socks5:
    type: socks5
    bind: 127.0.0.1:10888
    net: rule
net:
  socks5:
    type: socks5
    server: 127.0.0.1:1080
    net: local
  global:
    type: alias
    net: socks5
  rule:
    type: rule
    rule:
      - type: domain
        method: keyword
        target: socks5
        domain: twitter.com
      - type: domain
        method: keyword
        target: socks5
        domain: .twimg.com
      - type: domain
        method: keyword
        target: socks5
        domain: t.co
      - type: any
        target: local
      - type: any
        target: socks5
  direct:
    type: alias
    net: local
