version: "3"

volumes:
  tempo-data:
    driver: local
  loki-data:
    driver: local
  grafana-data:
    driver: local
services:

  tempo:
    image: grafana/tempo:latest
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./config/overrides.yaml:/etc/overrides.yaml
      - tempo-data/:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "14268:14268"  # jaeger ingest

  loki:
    image: grafana/loki:2.5.0
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    volumes:
      - loki-data:/loki
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  grafana:
    image: grafana/grafana:main   # track main as search is under active development
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  vector:
    image: timberio/vector:0.21.2-alpine
    volumes:
      - ./config/vector.toml:/etc/vector/vector.toml
    ports:
      - "9000"
    depends_on:
      - loki

  websocat-logs:
    image: mtilson/websocat:latest
    entrypoint: sh -c "websocat ws://192.168.233.1:8030/api/stream/logs | nc vector 9000"
    depends_on:
      - vector
    restart: unless-stopped

  websocat-traffic:
    image: mtilson/websocat:latest
    entrypoint: sh -c "websocat -B 1048576 ws://192.168.233.1:8030/api/stream/connection | nc vector 9000"
    depends_on:
      - vector
    restart: unless-stopped
